sudo: required 
language: cpp
services:
  - docker
before_install:
  - mkdir $(pwd)/build
  - docker pull spielhuus/buildimage:latest
  - sudo docker run -itd --name build -v $(pwd)/lightningcpp:/repo -v $(pwd)/build:/build spielhuus/buildimage
  - sudo docker exec build apt-get -y update
  - sudo docker exec build apt-get -y install libboost-all-dev libcurl4-openssl-dev libcurlpp-dev libssl-dev
  - sudo docker exec build git clone https://github.com/lightningcpp/lightningcpp.git /repo
script:
  - sudo docker exec build cmake -H/repo -B/build -Dbuild_tests=true
  - sudo docker exec build cmake --build /build
  - sudo docker exec build /build/test_lightningcpp
