sudo: required 
language: cpp




services:
  - docker
env:
  global:
    - secure: "q1K/p4qQQl2nceUb878ue3BNAPZDjBv5xPWVgtyefSV0isYv+0ZFtBttZVwojPFuS3zJtU8KtHomD/WjnniShGkI4V4QoTsM/4mBRXcoJdMv/pib9NLyNp2zFn9o16Rz1ZSMSkzqWsPASq9Pp1vJxSa2pmYjZ7enLCGXzOFuReVUPXtoaum6wUCAqEgwb/RGxcptz/eBATp4G5CkxSLFkRnZV/f+T3uxfmvCQb/FSoWvKDcHXtjDb2aumpFcecQ0eKXlzTprEnXV0fR8BzDmOQ1sJbYya58LLPnECFHJS2t5iwfAyvLsCrPGidRZBDr3p3fUF3rqWYLUjgwNlKnG6fe7mY9IqYuZzNADpLUTg/lH9S6dgjV4ioilX5wiaPc4fgwQVyLW6q611LBnbf20obc3o74DHjOhl53N+6Bl6Jnj9MtmsEfGqQgvGaMy/guQaNGTBHNVOaLbNRXCDED6g14Q1j+zYcGnFn/lD1Kuw9bJGmlBDVex9VziO/onXAvGh+jr5mKI/9Ir2Pu53BsmC7p3YMKXK585qR0X8LD9WIqnquCl915qVJBSC1OD35P//d2M4EDbfRs2cmN70+T44nuDm558gSFk6K7RfLD5IDdzEjd18vfA15V80AAhdpm6j/5po1IcwOq3vS9+EqYCf5ae4JNUVmI/FAqsahAQTHI=" #BINTRAY_KEY

before_install:
  - mkdir $(pwd)/build
  - docker pull spielhuus/buildimage:latest
  - sudo docker run -it -v $(pwd)/repo:/repo -v $(pwd)/build:/build spielhuus/toolchain /bin/bash -c "git clone https://github.com/lightningcpp/lightningcpp.git /repo && cd /build && conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan && conan remote add conan-cpp https://api.bintray.com/conan/squawkcpp/conan-cpp && conan install /repo --build=missing -s compiler.libcxx=libstdc++11 && cmake -H/repo -B/build -G Ninja -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja -Dbuild_tests=on -Dbuild_example_server=on -Dbuild_documentation=on && cmake --build /build && cmake --build /build --target test && cmake --build /build --target doc && cmake --build /build --target package && cd /repo/conan && conan export conan-cpp/latest && conan install lightningcpp/master@conan-cpp/latest --build=lightningcpp && conan user -p $BINTRAY_KEY -r conan-cpp squawkcpp && conan upload lightningcpp/master@conan-cpp/latest --all -r=conan-cpp"
