sudo: required
language: cpp
services:
- docker
env:
  global:
  - secure: q1K/p4qQQl2nceUb878ue3BNAPZDjBv5xPWVgtyefSV0isYv+0ZFtBttZVwojPFuS3zJtU8KtHomD/WjnniShGkI4V4QoTsM/4mBRXcoJdMv/pib9NLyNp2zFn9o16Rz1ZSMSkzqWsPASq9Pp1vJxSa2pmYjZ7enLCGXzOFuReVUPXtoaum6wUCAqEgwb/RGxcptz/eBATp4G5CkxSLFkRnZV/f+T3uxfmvCQb/FSoWvKDcHXtjDb2aumpFcecQ0eKXlzTprEnXV0fR8BzDmOQ1sJbYya58LLPnECFHJS2t5iwfAyvLsCrPGidRZBDr3p3fUF3rqWYLUjgwNlKnG6fe7mY9IqYuZzNADpLUTg/lH9S6dgjV4ioilX5wiaPc4fgwQVyLW6q611LBnbf20obc3o74DHjOhl53N+6Bl6Jnj9MtmsEfGqQgvGaMy/guQaNGTBHNVOaLbNRXCDED6g14Q1j+zYcGnFn/lD1Kuw9bJGmlBDVex9VziO/onXAvGh+jr5mKI/9Ir2Pu53BsmC7p3YMKXK585qR0X8LD9WIqnquCl915qVJBSC1OD35P//d2M4EDbfRs2cmN70+T44nuDm558gSFk6K7RfLD5IDdzEjd18vfA15V80AAhdpm6j/5po1IcwOq3vS9+EqYCf5ae4JNUVmI/FAqsahAQTHI=
before_install:
- sudo git clone https://github.com/lightningcpp/lightningcpp.git /lightning
script:
- sudo /bin/bash -c "cd /lightning && /bin/bash build.sh $BINTRAY_KEY $TRAVIS_BRANCH"
deploy:
  provider: releases
  api_key:
    secure: OO1+/n5AoT+vosctG/tgDcTL2myASDU1kimp1CMWu8jzfsfQjk6z9gDc3aVdn3BDOBm0rCis0BoOBmBRkWqD9Y/9eFHZ3DKADIUxOADIHhpKOfAmrd8p0vQRnDzHiz3bAlHd+mjsh53muCekd5SdRE1X2lxYdwXw/VJ6INQCIIu46fKaE7S9VGZFWIggSLNtW4ikMPCKVNoDztQq02Rstr7zNB8YJyKaxhmEwJs4VzVawq24bRRQtPZOyUJ+kwbE9P4zGcSXQBjk80hHCklKGqrgx4qBN+o89pK5eNFjuczjvyuyS9yx8ImOyW8hBg4GBiARifFcbm24CLH1ZDHWzFDNg/YXV601DFyBTylZMe8Xpz9rXModbNEjjtGfKhy7LVgR+hRwkXnX3iLXKc10WZMylPsPPRZ2lJ4UnS8BYfYswvAUbbTy9IDgcde1ukb606VOvXdBB7d57QCthAwTjrUCg1fKYyeAD9zw+n2mXHxN9tSayj4W2x4TbadtABTF4yJPX0go8KGh5X2W1lzmOuogG/xDHG2sswxvJz4X8wlhkIOfnWp4KzMD7TdO8XkOsGpFtohzO6RZzu2UzXZug3Nbd+yuyIR2sgNmgB2Ftrzwh6yD7zLPlIVLxjdVlZC9qUi9fm8IuOcyCUm4inc/VyrS+18wZzU5wgROaCYX2m8=
file: '$(pwd)/build/lightning_$TRAVIS_BRANCH.tar.gz'
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: lightningcpp/lightningcpp

