sudo: required 
language: cpp
services:
  - docker
before_install:
  - mkdir $(pwd)/build
  - docker pull spielhuus/buildimage:latest
  - sudo docker run -itd --name build -v $(pwd)/lightningcpp:/repo -v $(pwd)/build:/build spielhuus/buildimage
  - sudo docker exec build git clone https://github.com/lightningcpp/lightningcpp.git /repo
script:
  - sudo docker exec build cmake -H/repo -B/build -G Ninja -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja -Dbuild_tests=on
  - sudo docker exec build cmake --build /build
  - sudo docker exec build cmake --build /build --target test
